using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum SFXType  
{

    btnClick,
    Ring2,
    Touch,
    Scream,
    Laugh,
    Writing,
    Woosh_1,
    Woosh_2,
    Woosh_3,
    Woosh_4,
    Woosh_5,
    Woosh_6,
    Woosh_7,
    Screwing,
    BallWoosh1,
    BallFail,
    Walk,
    Bounce,
    Rim,
    TeacherAngry,
    CrowdLaughClap,
    VictoryClap,
    CrowdDisappointed,
    DisappointedGroup,
    FemaleSigh1,
    FemaeSigh2,
    MaleSigh1,
    MaleSigh2,
    Correct1,
    Correct2,
    Dance,
    WaterPour,
    VictoryClapShort,
    PickUpItem,
    DollarBonus,
    Incorrect,
    Threat,
    Punch1,
    Punch2,
    Punch3,
    Punch4,
    Punch5,
    PickCharacter,
    Scare,
    Scare_Female_1,
    Scare_Female_2,
    Scare_Female_3,
    Scare_Female_4,
    Scare_Female_5,
    Scare_Male_1,
    Scare_Male_2,
    Scare_Male_3,
    Scare_Male_4,
    Scare_Male_5,
    Victory,
    Lose,
    CleanBoard,
    hit,
    BowlingEnd,
    SoccerMiss,
    SoccerEnd,
    SoccerGoal,
    BonusShot,
    BigScore,
    Rocket,
    BasketballGameOver,
    none,

}
